### ISSUE TITLE
Trying to use exampleSite is unsuccessful

### ISSUE THREAD

**Issue by alexsannikov** [chrede88/L1nkr#175]
### What happened?

I want to try using L1nkr theme, and after installation I am copying the content of /exampleSite to the root folder. After that hugo complains with multiple errors.
I have installed on MacOS 10.15:
- hugo v0.138.0
- go v1.23.3
- L1nkr v1.9.2

Steps: 
1. Create new site with 'hugo new site lnk && cd lnk/themes'
2. Clone L1nkr theme with 'git clone https://github.com/chrede88/L1nkr.git'
3. Add " theme = 'L1nkr' " to hugo.toml in the project's root
4. Copy all content from /themes/L1nkr/exampleSite to project's root folder with replacement (where necessary)
5. Adjustment in go.mod file required regarding the module path, as otherwise module 'github.com/chrede88/L1nkr' can't be found.
After that, I issue the hugo server -D and see errors and warnings:
1. WARN  Module "L1nkr" is not compatible with this Hugo version: Min 0.119.0 extended; <...>
2. ERROR render of "home" failed: <...>
3. Error: error building site: render: failed to render pages: <...>
Please see full log output below. 

Questions: why hugo says that theme is not compatible and complains about version, while I have latest one? Why it as well complains that some feature is not available in my version?
Thanks, 
Alexey

### Theme version

v1.9.2

### Hugo version

v0.138.0

### Which browser are you using?

Firefox

### Relevant Hugo log output

```shell
14:46:04 server: [lnk] $ hugo server -D
WARN  Module "L1nkr" is not compatible with this Hugo version: Min 0.119.0 extended; run "hugo mod graph" for more information.
Watching for changes in /Users/Alexey/hugo-workshops/lnk/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/Alexey/hugo-workshops/lnk/hugo.toml, /Users/Alexey/hugo-workshops/lnk/config/_default, /Users/Alexey/hugo-workshops/lnk/hugo.toml, /Users/Alexey/hugo-workshops/lnk/config/_default, /Users/Alexey/hugo-workshops/lnk/themes/L1nkr/hugo.yaml, /Users/Alexey/hugo-workshops/lnk/go.mod
Start building sites … 
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9 darwin/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=gohugoio

ERROR render of "home" failed: "/Users/Alexey/hugo-workshops/lnk/themes/L1nkr/layouts/_default/baseof.html:10:11": execute of template failed: template: index.html:10:11: executing "index.html" at <partial "header" .>: error calling partial: "/Users/Alexey/hugo-workshops/lnk/themes/L1nkr/layouts/partials/header.html:7:22": execute of template failed: template: partials/header.html:7:22: executing "partials/header.html" at <$image.Filter>: error calling Filter: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 19 ms
Error: error building site: render: failed to render pages: render of "404" failed: "/Users/Alexey/hugo-workshops/lnk/themes/L1nkr/layouts/_default/baseof.html:10:11": execute of template failed: template: 404.html:10:11: executing "404.html" at <partial "header" .>: error calling partial: "/Users/Alexey/hugo-workshops/lnk/themes/L1nkr/layouts/partials/header.html:7:22": execute of template failed: template: partials/header.html:7:22: executing "partials/header.html" at <$image.Filter>: error calling Filter: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
14:46:11 server: [lnk] $
```

**Comment by chrede88** [comment]
Please use the template, as stated in the [README](https://github.com/chrede88/L1nkr/blob/main/README.md).

**Comment by alexsannikov** [comment]
Thanks for reply. I followed the provided link, and instruction doesn't work for me. Maybe, I missed something.

First of all, I created new site in hugo. Then I followed the link leading me to the Template (not theme). I've read "Installation" topic and repeated all the steps as described.

>>>Use this template by pressing Use this template. Don't fork this repository!
Done. I've created my own repo and all the files were copied there.
>>>Wait 20s-30s and update the page. The files in your repo are getting populated.
Done.
>>>Add a LICENSE to your repo.
Added.
>>>Clone your version of the template to your local computer:
>>>git clone https://github.com/<username>/<reponame>
I executed this command in the root folder of my freshly created site, and git downloaded my repo as an additional folder with the repo name into the whole site structure.
>>>Change the module name to match your github repo in go.mod.
Changed to the 'github.com/<username>/<reponame>' without quotes and substituted my username and reponame
>>>Modify config/_default/hugo.yaml and config/_default/params.yaml according to the configuration below.
What means 'below'? maybe 'above'? Anyway, I replaced one line with the link to my repo in hugo.yaml file, couldn't find what to replace in params.file and where. Opposite to hugo.yaml, there's no specific section description where replacement is required.
>>>All images are stored in the assets/ folder. You can group in subfolders if you like.
Skipped just to run site and see overall structure
>>>Build a local version of your site by executing hugo server. You can see the site by navigating to localhost:1313 (actual URL will be outputted in the CLI) in a browser.
>>>Add a new icon.png file to update the favicon. The png file should be 512px by 512px in size.
Started hugo server -D.

Result: site is working. Main page says 'Page Not Found'.

Thanks in advance for any help and support.

**Comment by alexsannikov** [comment]
Version of my hugo is extended
** $ hugo version
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended darwin/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=gohugoio**

**Comment by chrede88** [comment]
I'll take a look when I get home later today.

**Comment by chrede88** [comment]
I've tweaked the Template cleanup workflow. It was for some reason not executing anymore.
I tried to use the template myself and everything works as expected. This is what I did:
1. Created a new repo by pressing `Use this template`.
2. After repo is created I waited 10s, then reloaded the page. A new commit should've been created. You can check under `Actions`. The `Clean Template` workflow should have executed successfully.
3. Clone the repo to my local machine.
4. execute `hugo server` and open the site in my browser.


I'm also using `hugo v0.138.0 extented`.

Please try to create a new repo using the template once more. If it still doesn't work, please add a link to the repo so I can clone and try myself.

**Comment by alexsannikov** [comment]
I've just re-tried all the steps. The instruction is generated during the repo's creation, all the changes in files were applied automatically.

*1. Created a new repo by pressing Use this template.*
Done.
*Add a LICENSE to your repo.*
Done.
*Clone your version of the template to your local computer:
git clone https://github.com/alexsannikov/l1nkrTemplate*
Done.
** 09:53:50 server: [hugo-workshops] $ hugo new site l1nkr
Congratulations! Your new Hugo site was created in /Users/Alexey/hugo-workshops/l1nkr.

Just a few more steps...

1. Change the current directory to /Users/Alexey/hugo-workshops/l1nkr.
2. Create or install a theme:
   - Create a new theme with the command "hugo new theme <THEMENAME>"
   - Or, install a theme from https://themes.gohugo.io/
3. Edit hugo.toml, setting the "theme" property to the theme name.
4. Create new content with the command "hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>".
5. Start the embedded web server with the command "hugo server --buildDrafts".

See documentation at https://gohugo.io/.
09:53:51 server: [hugo-workshops] $ cd l1nkr/
09:58:40 server: [l1nkr] $ git clone https://github.com/alexsannikov/l1nkrTemplate
Cloning into 'l1nkrTemplate'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 44 (delta 8), reused 29 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (44/44), done.
09:58:47 server: [l1nkr] $ **
*Modify config/_default/hugo.yaml and config/_default/params.yaml according to the configuration below.*
Not required, as I see all necessary changes were made already during the repo's creation
*Build a local version of your site by executing hugo server. You can see the site by navigating to http://localhost:1313/l1nkrTemplate/ (actual URL will be outputted in the CLI) in a browser.*
**10:00:07 server: [l1nkr] $ hugo server
Watching for changes in /Users/Alexey/hugo-workshops/l1nkr/{archetypes,assets,content,data,i18n,layouts,static}
Watching for config changes in /Users/Alexey/hugo-workshops/l1nkr/hugo.toml
Start building sites … 
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended darwin/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=gohugoio

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  4  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Cleaned          |  0  

Built in 4 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop**
Following the link http://localhost:1313/l1nkrTemplate/ site says "Page Not Found"

**Comment by alexsannikov** [comment]
Also I found "Renovate" job failed...

**Comment by chrede88** [comment]
> Also I found "Renovate" job failed...

That's fine. I'm using Renovate to update stuff in the main repo. This workflow get removed once the `Template Clean` workflow runs.

**Comment by chrede88** [comment]
Glad it worked out for you 👍
