### ISSUE TITLE
Custom SVG icon

### ISSUE THREAD

**Issue by xyko0** [chrede88/L1nkr#34]
### What happened?

Hi, I'm trying to make L1nker to work for my team and I would like to add a custom SVG icon as explained in the README. 
Sadly, I must miss with something as I have the good icon but not with the good size. 
See below :
![image](https://github.com/chrede88/L1nkr/assets/52315700/2b2c4ada-208e-4028-88b4-5419d0a8ae59)
Can you explain what I'm doing wrong ?
SVG file should be in a fixed size ?
Thanks

### Theme version

v1.8.0

### Hugo version

0.120.4

### Which browser are you using?

Chrome

**Comment by xyko0** [comment]
You don't get me, this is a link icon.

**Comment by chrede88** [comment]
I see. Can you provide some more info then. What did you name this file, where did you put it and how did you reference it in your `params.yaml` config file.

**Comment by chrede88** [comment]
Can you dump a link to your repo? Then I can try to see if I can figure out what's going wrong. It's seems like you're doing everything correctly, so I don't really know what to suggest without being able to play around with it myself.

**Comment by xyko0** [comment]
I cannot share my repository with you as I'm working for a private company on a private gitlab 😢 
But here's the image I use, on the repo I forked from yours (I know this is useless for the build, we use the template) https://github.com/xyko0/L1nkr/blob/main/assets/icons/CTRLM_Prod.svg
Maybe you'll see something trying to build a link with my SVG image ?

**Comment by chrede88** [comment]
Okay, I had a look at your icon. Two things stand out:
1) The icon size is hardcoded. If you open your icon as code and look at the second line:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300px" height="300px" viewBox="0 0 300 300" version="1.1">
```
Notice that `width` and `height` are both `300px`. This means that the size can't be changed. Change both to `100%`.

2) The `<path>` sections have a `style` defined. This means the css classes the theme defines can't change the color etc.
Just remove the styles on all `<path>` sections to fix this issue.

This is what I get if I do that:
<img width="540" alt="Screenshot 2023-11-29 at 5 01 19 PM" src="https://github.com/chrede88/L1nkr/assets/9137189/e8633dd7-0705-45ea-b7d4-47c1660bba7f">

**Comment by xyko0** [comment]
Insane ! It works very well, thank you so much for your time 😄 
Keep going my friend this project is very cool 👍
